.TH GOXF 1 "November 18, 2010"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
goxf \- 0xFFFF GUI
.SH SYNOPSIS
.B goxf
.RB [FILE]
.SH DESCRIPTION
This utility is a graphical interface to 0xFFFF. It is used to
communicate with the NOLO bootloader of Nokia's internet tablets
(770, N800, N810, N900).
.SH OPTIONS
goxf takes no options.
.SH SEE ALSO
.B 0xFFFF(1)
.SH AUTHOR
goxf was written by pancake.
.PP
This manual page was written by Sebastian Reichel <elektranox@gmail.com>,
for the Debian project (but may be used by others).
